<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="1" ignored="0" total="3" passed="1">
  <reporter-output>
    <line>
      <![CDATA[First reporter string]]>
    </line>
    <line>
      <![CDATA[Second reporter string]]>
    </line>
  </reporter-output>
  <suite name="Default suite" duration-ms="190" started-at="2018-09-30T19:50:36Z" finished-at="2018-09-30T19:50:36Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="190" started-at="2018-09-30T19:50:36Z" finished-at="2018-09-30T19:50:36Z">
      <class name="com.scp.test.NewTest">
        <test-method status="PASS" signature="setupLogger()[pri:0, instance:com.scp.test.NewTest@27efef64]" name="setupLogger" is-config="true" duration-ms="112" started-at="2018-10-01T01:20:36Z" finished-at="2018-10-01T01:20:36Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setupLogger -->
        <test-method status="FAIL" signature="f()[pri:0, instance:com.scp.test.NewTest@27efef64]" name="f" duration-ms="15" started-at="2018-10-01T01:20:36Z" finished-at="2018-10-01T01:20:36Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Contents are not matching expected [Nitishr] but found [Nitish]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Contents are not matching expected [Nitishr] but found [Nitish]at org.testng.Assert.fail(Assert.java:96)at org.testng.Assert.failNotEquals(Assert.java:776)at org.testng.Assert.assertEqualsImpl(Assert.java:137)at org.testng.Assert.assertEquals(Assert.java:118)at org.testng.Assert.assertEquals(Assert.java:453)at com.scp.test.NewTest.f(NewTest.java:26)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)at java.lang.reflect.Method.invoke(Unknown Source)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[First reporter string]]>
            </line>
          </reporter-output>
        </test-method> <!-- f -->
        <test-method status="PASS" signature="G()[pri:0, instance:com.scp.test.NewTest@27efef64]" name="G" duration-ms="5" started-at="2018-10-01T01:20:36Z" finished-at="2018-10-01T01:20:36Z">
          <reporter-output>
            <line>
              <![CDATA[Second reporter string]]>
            </line>
          </reporter-output>
        </test-method> <!-- G -->
        <test-method status="SKIP" signature="H()[pri:0, instance:com.scp.test.NewTest@27efef64]" name="H" duration-ms="0" started-at="2018-10-01T01:20:36Z" depends-on-methods="com.scp.test.NewTest.f" finished-at="2018-10-01T01:20:36Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method NewTest.H()[pri:0, instance:com.scp.test.NewTest@27efef64] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method NewTest.H()[pri:0, instance:com.scp.test.NewTest@27efef64] depends on not successfully finished methodsat org.testng.internal.Invoker.invokeTestMethods(Invoker.java:878)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- H -->
      </class> <!-- com.scp.test.NewTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
